name: lingostream
description: AI Live Screen and Voice Translator supported by Google Ads.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  package_info_plus: ^8.0.0
  google_mobile_ads: ^5.1.0  # Офіційна бібліотека Google AdMob

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
