name: lingostream
description: "A professional IPTV stream translator and media player with local storage support."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
